services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - ml-service
      - mongodb
    environment:
      - ML_SERVICE_URL=http://ml-service:8000
      - MONGODB_URI=mongodb://mongodb:27017/nail_design

  ml-service:
    build:
      context: ./ml-service/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ml-service/app/uploads:/app/uploads
      - ./ml-service/app/designs:/app/designs
      - ./ml-service/app/results:/app/results
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/nail_design_db

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

