version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - ml-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/nail_design_db
      ML_SERVICE_URL: http://ml-service:8000
      SERVER_URL: http://172.20.10.7:8080
    volumes:
      - ./uploads:/app/uploads

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
volumes:
  mongo_data: